FROM ubuntu:24.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        git \
        sudo \
        debianutils \
        python3-pip \
        python3-virtualenv \
        python3-venv \
        python3-dev \
        libevent-dev \
        libffi-dev \
        libxml2-dev \
        libxslt-dev \
        zlib1g-dev && \
    DEBIAN_FRONTEND=noninteractive apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/ceph/s3-tests.git /opt/s3-tests

    
WORKDIR /opt/s3-tests
RUN python3 -m venv .venv && \
    . .venv/bin/activate && \
    pip install tox

ENV VIRTUAL_ENV="/opt/s3-tests/.venv" \ 
    PATH="/opt/s3-tests/.venv/bin:$PATH"


ENTRYPOINT ["/bin/bash", "-c"]
CMD ["exec python3 -m tox"]
